### ISSUE TITLE
Btree.py not found

### ISSUE THREAD

**Issue by laiyuzhi** [imitrob/teleop_gesture_toolbox#1]
Hello, I have interest with your project. In which script you describe the behavior tree? I cannot find a script like "Btree.py"

**Comment by laiyuzhi** [comment]
from context_based_gesture_operation.msg import Scene as SceneRos
from context_based_gesture_operation.msg import Gestures as GesturesRos
from context_based_gesture_operation.srv import BTreeSingleCall

sys.path.append(get_cbgo_path())
from context_based_gesture_operation.srcmodules.Actions import Actions
from context_based_gesture_operation.srcmodules.Scenes import Scene
from context_based_gesture_operation.srcmodules.Objects import Object, Cup, Drawer

In otherwords I cannot find "context_based_gesture_operation"

**Comment by petrvancjr** [comment]
Hello, sorry for late response. New commit 6066c8151e17dac7f16fa5440e2efbb01dc6c50e should solve this issue.

Let me know if that helped, thank you!
