### ISSUE TITLE
Cant Acesses gitlab 

### ISSUE THREAD

**Issue by ARCARCARC1** [imitrob/teleop_gesture_toolbox#2]
I recevied the following error (see picture below) while running the following code from teleop_gesture_toolbox/include/scripts
/installation.sh . Is there anyway to resolve this?

```
git clone git@gitlab.ciirc.cvut.cz:imitrob/mirracle/teleop_gesture_toolbox.git
git clone git@gitlab.ciirc.cvut.cz:imitrob/mirracle/coppelia_sim_ros_interface.git
```

![22 11 2023_14 59 57_REC](https://github.com/imitrob/teleop_gesture_toolbox/assets/151715824/2ee6b5e1-94e7-4808-a0e8-580f85ae98a3)

Thank you!

**Comment by petrvancjr** [comment]
Hello, sorry for using private link. New commit 6066c8151e17dac7f16fa5440e2efbb01dc6c50e should solve this issue.

Have a great day!
