### ISSUE TITLE
Errors with sever_run.py and btree.py when launching backend.launch

### ISSUE THREAD

**Issue by ARCARCARC1** [imitrob/teleop_gesture_toolbox#4]
Dear Petr,

I am facing the issues below when running `ros2 launch teleop_gesture_toolbox backend.launch` and it seems like there are missing files. May I know if you have faced the same issues as well? 
![image](https://github.com/imitrob/teleop_gesture_toolbox/assets/151715824/ff33f87a-a9f5-48a1-b494-a9940a093ee6)

Warm regards,
Jun Jie

**Comment by petrvancjr** [comment]
Hello,

please download the given file in [link](https://drive.google.com/file/d/1miZZH9db0C7EG06j72JrZJe7Gkd6qAVV/view) or run following script ([link](https://github.com/imitrob/context_based_gesture_operation/blob/main/context_based_gesture_operation/download_sample.py)) from original folder, this should download network model into `trained_networks` folder automatically. 

I'm adding a few additional notes:
- `backend.launch` starts the `g2i.py` node which is set to start _context-based_ mapping by default. [Here](https://github.com/imitrob/context_based_gesture_operation/blob/f23e99a94a16f8558d03aff9a6cec5e84af04caf/context_based_gesture_operation/agent_nodes/g2i.py#L409), the simple 1-to-1 mapping can be launched instead  when argument `inference_type='1to1'`.
- NN model can be generated using notebooks [nb11_dataset_generation_complete.ipynb](https://github.com/imitrob/context_based_gesture_operation/blob/main/context_based_gesture_operation/nb11_dataset_generation_complete.ipynb) and [nb12_model_classification_complete.ipynb](https://github.com/imitrob/context_based_gesture_operation/blob/main/context_based_gesture_operation/nb12_model_classification_complete.ipynb).

Thank you for sending these issues, they are really appreciated.
Petr
